// src/app/dev/dev-panel-reload/dev-panel-reload.component.ts
import { Component } from '@angular/core';
import { Bitrix24Service } from '../../services/bitrix24.service';

@Component({
  selector: 'dev-panel-reload',
  standalone: true,
  imports: [],
  templateUrl: './dev-panel-reload.component.html',
})
export class DevPanelReloadComponent {
  constructor(private bitrixService: Bitrix24Service) {
    bitrixService.BX24?.bind(window, 'keydown', (e: KeyboardEvent) => {
      if (e.ctrlKey && e.code === 'KeyR') {
        e.preventDefault();
        this.reload();
      }
    });
  }

  reload() {
    window.location.reload();
  }
}

<a href="#" title="Обновить (Ctrl+R)">&#x21bb;</a>

// src/components/dev/DevPanelReload.vue
<template>
  <a href="#" title="Обновить (Ctrl+R)" @click.prevent="reload">&#x21bb;</a>
</template>

<script>
export default {
  methods: {
    reload() {
      window.location.reload();
    },
  },
  created() {
    this.$BX24.bind(window, 'keydown', (e) => {
      if (e.ctrlKey && e.code === 'KeyR') {
        e.preventDefault();
        this.reload();
      }
    });
  },
  inject: ['$BX24'],
  name: 'dev-panel-reload',
};
</script>
