// src/app/dev/dev-panel-download/dev-panel-download.component.ts
import { Component } from '@angular/core';
import config from '../../../config';

@Component({
  selector: 'dev-panel-download',
  standalone: true,
  imports: [],
  templateUrl: './dev-panel-download.component.html',
})
export class DevPanelDownloadComponent {
  get dirname() {
    return [config.path, config.global.archiveName].join('');
  }

  get filename() {
    return `${config.global.appDirName}, ${new Date().toLocaleString()}.zip`;
  }
}

<a
  href="dirname"
  download="filename"
  title="Скачать последнюю версию"
>&#10515;</a>

// src/components/dev/DevPanelDownload.vue
<template>
  <a
    :href="dirname"
    :download="filename"
    title="Скачать последнюю версию"
  >&#10515;</a>
</template>

<script>
import config from '../../config';

export default {
  computed: {
    dirname() {
      return [config.path.root, config.global.archiveName].join('');
    },
    filename() {
      return `${config.global.appDirName}, ${new Date().toLocaleString()}.zip`;
    },
  },
  name: 'dev-panel-download',
};
</script>
