// src/app/components/card/card.component.ts
import { v4 as uuid } from 'uuid';
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { IconComponent } from '../icon/icon.component';

@Component({
  selector: 'app-card',
  standalone: true,
  imports: [FormsModule, IconComponent],
  templateUrl: './card.component.html',
  styleUrl: './card.component.scss',
})
export class CardComponent {
  @Output() public remove: EventEmitter<void> = new EventEmitter<void>();
  @Output() public toggle: EventEmitter<boolean> = new EventEmitter<boolean>();
  @Input({ required: true }) public icon: string;
  @Input({ required: true }) public title: string;
  @Input({ required: true }) public size: string;
  @Input() public isCustom: boolean = false;
  public id: string = uuid();
  public active: boolean = true;

  onRemove(e: Event): void {
    e.stopPropagation();
    this.remove.emit();
  }

  onToggle(e: Event): void {
    this.toggle.emit((<HTMLInputElement>e.target).checked);
  }

  getIcon(icon: string) {
    const fullPath = ['assets/', icon].join('');
    return icon.includes('http') ? icon : fullPath;
  }
}

<div class="card" [class]="{ disabled: !active }" [title]="title">
  <header class="card__header">
    @if (isCustom) {
      <app-icon
        class="card__icon"
        name="close-circle"
        title="Удалить стикер из вашего браузера"
        (click)="onRemove($event)"
      ></app-icon>
    } @else {
      <input
        [(ngModel)]="active"
        [id]="id"
        type="checkbox"
        title="Отключить стикер при копировании кода"
        (click)="onToggle($event)"
      />
    }
  </header>
  <label [for]="id" class="card__label">
    <img
      class="card__image"
      [src]="getIcon(icon)"
      [alt]="title"
      [style]="{
        width: size ? size+'px' : null,
        height: size ? size+'px' : null,
      }"
    />
  </label>
</div>

// src/components/Card.vue
<template>
  <div class="card" :class="{ disabled: !active }" :title="title">
    <header class="card__header">
      <app-icon
        v-if="isCustom"
        class="card__icon"
        name="close-circle"
        title="Удалить стикер из вашего браузера"
        @click.stop="$emit('remove')"
      ></app-icon>
      <input
        v-else
        v-model="active"
        :id="id"
        type="checkbox"
        title="Отключить стикер при копировании кода"
        @click="$emit('toggle', $event.target.checked)"
      >
    </header>
    <label :for="id" class="card__label">
      <img
        class="card__image"
        :src="icon"
        :alt="title"
        :style="{
          width: size ? `${size}px` : null,
          height: size ? `${size}px` : null,
        }"
      >
    </label>
  </div>
</template>

<script>
import { v4 as uuid } from 'uuid';
import AppIcon from './Icon.vue';

export default {
  data() {
    return {
      id: uuid(),
      active: this.selected,
    };
  },
  props: {
    icon: {
      type: String,
      required: true,
    },
    title: {
      type: String,
      required: true,
    },
    size: {
      type: String,
      required: true,
    },
    isCustom: {
      type: Boolean,
      default: false,
    },
    selected: {
      type: Boolean,
      default: false,
    },
  },
  components: {
    AppIcon,
  },
  name: 'app-card',
};
</script>

<style lang="stylus">
@require '../assets/smartgrid.styl'

.card
  text-align center
  &:hover
  &.disabled
    opacity .5
  &__header
    display flex
    justify-content space-between
    align-content center
    margin-bottom 5px
  &__icon
    cursor pointer
  &__label
    display inline-block
    max-width 200px
  &__image
    max-width 100%
    height auto
    cursor pointer
</style>
