// src/app/components/panel/panel.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { ButtonComponent } from '../button/button.component';
import { PopupComponent } from '../popup/popup.component';
import { Bitrix24Service } from '../../services/bitrix24.service';
import { BitrixBatch } from '../../../api/bitrix';
import { ISticker } from '../../../packs';
import { IPlacement } from '../../../types/bx24';

@Component({
  selector: 'app-panel',
  standalone: true,
  imports: [ButtonComponent, PopupComponent],
  templateUrl: './panel.component.html',
  styleUrl: './panel.component.scss',
})
export class PanelComponent implements OnInit {
  @Output() public addSticker: EventEmitter<ISticker> =
    new EventEmitter<ISticker>();
  @Output() public closePopup: EventEmitter<void> = new EventEmitter<void>();
  @Input() public isPopup: boolean = false;
  public isLoaded: boolean = false;
  public isInstall: boolean = false;
  protected readonly $BX24: any = null;
  private batch: any = null;

  constructor(private bitrixService: Bitrix24Service) {
    this.$BX24 = bitrixService.BX24;
  }

  ngOnInit(): void {
    if (this.$BX24) {
      this.batch = new BitrixBatch(this.$BX24);
      this.init();
    }
  }

  uninstall() {
    this.isLoaded = false;

    this.batch.deleteApp().then(() => {
      this.isInstall = false;
      this.isLoaded = true;
    });
  }

  install() {
    this.isLoaded = false;

    this.batch.app().then(() => {
      this.isInstall = true;
      this.isLoaded = true;
    });
  }

  init() {
    this.batch.getList().then(({ list }: any) => {
      const isApp = (<IPlacement[]>list).find(
        (item) => item.placement === 'IM_SMILES_SELECTOR',
      );

      this.isInstall = Boolean(isApp);
      this.isLoaded = true;
    });
  }

  onAddSticker(sticker: ISticker): void {
    this.addSticker.emit(sticker);
  }

  onClosePopup(): void {
    this.closePopup.emit();
  }
}

<div class="panel">
  <div class="panel__item left">
    <ng-content></ng-content>
  </div>
  @if ($BX24 && isLoaded) {
    <div class="panel__item right">
      @if (isInstall) {
        <app-button (click)="uninstall()">Удалить стикеры из чата</app-button>
      } @else {
        <app-button (click)="install()">Установить стикеры в чат</app-button>
      }
    </div>
  }
  @if (isPopup) {
    <app-popup
      (add)="onAddSticker($event)"
      (close)="onClosePopup()"
    ></app-popup>
  }
</div>

// src/components/Panel.vue
<template>
  <div class="panel">
    <div class="panel__item left">
      <slot></slot>
    </div>
    <div v-if="$BX24 && isLoaded" class="panel__item right">
      <app-button v-if="isInstall" @click="uninstall">Удалить стикеры из чата</app-button>
      <app-button v-else @click="install">Установить стикеры в чат</app-button>
    </div>
    <teleport to="#modals">
      <app-popup
        v-if="isPopup"
        @add="$emit('add-sticker', $event)"
        @close="$emit('close-popup')"
      ></app-popup>
    </teleport>
  </div>
</template>

<script>
import AppButton from './Button.vue';
import AppPopup from './Popup.vue';
import BitrixBatch from '../api/bitrix';

export default {
  methods: {
    uninstall() {
      this.isLoaded = false;

      this.$options.batch.deleteApp().then(() => {
        this.isInstall = false;
        this.isLoaded = true;
      });
    },
    install() {
      this.isLoaded = false;

      this.$options.batch.app().then(() => {
        this.isInstall = true;
        this.isLoaded = true;
      });
    },
    init() {
      this.$options.batch.getList().then(({ list }) => {
        const isApp = list.find((item) => item.placement === 'IM_SMILES_SELECTOR');

        this.isInstall = Boolean(isApp);
        this.isLoaded = true;
      });
    },
  },
  mounted() {
    if (this.$BX24) {
      this.$options.batch = new BitrixBatch(this.$BX24, this.$BX24.isAdmin());
      this.init();
    }
  },
  data() {
    return {
      isLoaded: false,
      isInstall: false,
    };
  },
  batch: null,
  inject: ['$BX24'],
  props: {
    isPopup: {
      type: Boolean,
      default: false,
    },
  },
  components: {
    AppButton,
    AppPopup,
  },
  name: 'app-panel',
};
</script>

<style lang="stylus">
@require '../assets/smartgrid.styl'

.panel
  display flex
  justify-content space-between
  align-items center
  column-gap 10px
  margin 10px 0
  &__item
    display flex
    flex-wrap wrap
    column-gap 5px
    &.right
      justify-content flex-end
</style>
