// src/app/chat.component.ts
import { Component } from '@angular/core';
import { Bitrix24Service } from './services/bitrix24.service';
import { ApiService } from './services/api.service';
import { BitrixBatch } from '../api/bitrix';
import stickers, { IStickerPack, marketplace } from '../packs';

@Component({
  selector: 'app-chat',
  standalone: true,
  imports: [],
  templateUrl: './chat.component.html',
  styleUrl: './chat.component.scss',
})
export class ChatComponent {
  public linkToApp: string = '';
  public state: 'default' | 'marketplace' = 'default';
  public customStickers: IStickerPack = {
    title: 'Свои стикеры',
    link: '',
    list: [],
  };
  public size: number = 100;
  private readonly $BX24: any = null;

  constructor(
    private bitrixService: Bitrix24Service,
    private apiService: ApiService,
  ) {
    this.customStickers.list = this.apiService.getStickers();
    this.$BX24 = this.bitrixService.BX24;

    const RestCall = this.$BX24.createBatch();
    RestCall.batch({
      appInfo: ['app.info'],
    })
      .then(({ appInfo }: any) => {
        this.linkToApp = `${this.$BX24.getDomain(true)}/marketplace/app/${appInfo.CODE}/`;
      })
      .catch(console.warn);

    this.bitrixService.BX24?.bind(window, 'keydown', (e: KeyboardEvent) => {
      if (e.ctrlKey && e.shiftKey && e.code === 'KeyT') {
        e.preventDefault();
        this.state = this.isMarketplace ? 'default' : 'marketplace';
      }
    });
  }

  get stickers(): IStickerPack[] {
    return this.isMarketplace ? marketplace : stickers;
  }

  get isMarketplace() {
    return this.state === 'marketplace';
  }

  sendMessage(
    icon: string,
    title: string = 'Noname Sticker',
    size: number | string = this.size,
  ) {
    const { options } = this.$BX24.placement.info();
    const batch = new BitrixBatch(this.$BX24);

    return batch
      .sendMessage(
        options.dialogId,
        `[icon=${this.getIcon(icon)} size=${size} title=${title}]`,
      )
      .catch(console.warn);
  }

  getStyle(size: number | string = this.size) {
    return {
      height: `${size}px`,
      cursor: 'pointer',
    };
  }

  getIcon(icon: string) {
    const site = [window.location.origin, window.location.pathname]
      .join('')
      .replace('index.html', '');
    const fullPath = [site, 'assets/', icon].join('');
    return icon.includes('http') ? icon : fullPath;
  }
}

<div class="howto">
  <span class="howto__item">
    <img
      src="./assets/free-icon-mouse-left-button.png"
      alt="ЛКМ"
      title="Левая кнопка мыши"
    />
    — отправить в чат
  </span>
</div>
<div class="pack">
  <h3>{{ customStickers.title }}</h3>
  @if (linkToApp) {
    <a [href]="linkToApp" target="_blank" class="link" title="Перейти в приложение">
      +
    </a>
  }
  <ul class="stickers">
    @for (sticker of customStickers.list; track $index) {
      <li (click)="sendMessage(sticker.icon, sticker.title, sticker.size)">
        <img
          [src]="getIcon(sticker.icon)"
          [alt]="sticker.title"
          [title]="sticker.title"
          [style]="getStyle(sticker.size)"
        />
      </li>
    }
  </ul>
</div>
@for (pack of stickers; track $index) {
  <div class="pack">
    <h3>{{ pack.title }}</h3>
    <ul class="stickers">
      @for (sticker of pack.list; track $index) {
        <li (click)="sendMessage(sticker.icon, sticker.title, sticker.size)">
          <img
            [src]="getIcon(sticker.icon)"
            [alt]="sticker.title"
            [title]="sticker.title"
            [style]="getStyle(sticker.size)"
          />
        </li>
      }
    </ul>
  </div>
}

// src/Chat.vue
<template>
  <div class="howto">
    <span class="howto__item">
      <img
        src="./assets/free-icon-mouse-left-button.png"
        alt="ЛКМ"
        title="Левая кнопка мыши"
      > — отправить в чат
    </span>
  </div>
  <div v-if="customStickers.list.length" class="pack">
    <h3>{{ customStickers.title }}</h3>
    <ul class="stickers">
      <li
        v-for="(sticker, key) in customStickers.list"
        :key="key"
        @click="sendMessage(sticker.icon, sticker.title, sticker.size)"
      >
        <img
          :src="getIcon(sticker.icon)"
          :alt="sticker.title"
          :title="sticker.title"
          :style="getStyle(sticker.size)"
        >
      </li>
    </ul>
  </div>
  <div
    v-for="(pack, key) in stickers"
    :key="key"
    class="pack"
  >
    <h3>{{ pack.title }}</h3>
    <ul class="stickers">
      <li
        v-for="(sticker, key) in pack.list"
        :key="key"
        @click="sendMessage(sticker.icon, sticker.title, sticker.size)"
      >
        <img
          :src="getIcon(sticker.icon)"
          :alt="sticker.title"
          :title="sticker.title"
          :style="getStyle(sticker.size)"
        >
      </li>
    </ul>
  </div>
</template>

<script>
import config from './config';
import stickers, { marketplace } from './packs';
import api from './api';
import BitrixBatch from './api/bitrix';

export default {
  methods: {
    sendMessage(icon, title = 'Noname Sticker', size = this.size) {
      const { options } = this.$BX24.placement.info();
      const batch = new BitrixBatch(this.$BX24, this.$BX24.isAdmin());

      return batch.sendMessage(options.dialogId, `[icon=${this.getIcon(icon)} size=${size} title=${title}]`)
        .catch(window.console.warn);
    },
    getStyle(size = this.size) {
      return {
        height: `${size}px`,
        cursor: 'pointer',
      };
    },
    getIcon(icon) {
      const fullPath = [config.path, icon].join('');
      return icon.includes('http') ? icon : fullPath;
    },
  },
  computed: {
    stickers() {
      if (this.state === 'marketplace') return marketplace;
      return stickers;
    },
  },
  created() {
    document.addEventListener('keydown', (e) => {
      if (e.ctrlKey && e.shiftKey && e.code === 'KeyT') {
        e.preventDefault();
        this.state = this.state === 'marketplace' ? 'default' : 'marketplace';
      }
    });
  },
  data() {
    return {
      state: 'marketplace', // default,marketplace
      customStickers: {
        title: 'Свои стикеры',
        list: api.get(),
      },
      size: 100,
    };
  },
  inject: ['$BX24'],
  name: 'app-chat',
};
</script>

<style lang="stylus">
html
  font-family Roboto, sans-serif
  overflow initial
#app
  min-width initial
  margin 5px
.howto
  background-color #ffffff
  &__item
    display flex
    align-items center
.pack
  h3
    display inline-block
    background-color #ffffff
  a.link
    padding 10px
    border-radius 4px
    box-shadow 0 3px 1px -2px #0003,0 2px 2px #00000024,0 1px 5px #0000001f
    height 70px
    width 70px
    display inline-block
    text-align center
    line-height 2
    color #000
    background-color rgba(#fff, .4)
    text-decoration none
    font-size 35px
    &:hover
      background-color #fff
.stickers
  display flex
  flex-wrap wrap
  column-gap 5px
  list-style-type none
  padding-left 0
</style>
